# Generated by Django 3.0.6 on 2020-06-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Duty', '0002_auto_20200612_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duty_m',
            name='duty',
            field=models.IntegerField(choices=[(0, '出勤'), (1, '祝日'), (2, '早退'), (3, '遅刻'), (4, 'シフト'), (5, '休出'), (6, '欠勤'), (7, '年休'), (8, '振休')], default=0, verbose_name='出勤状态'),
        ),
        migrations.AlterField(
            model_name='duty_m',
            name='rest',
            field=models.TimeField(default='1:00', verbose_name='休憩時間'),
        ),
    ]
